const fs=require('fs'),vm=require('vm'),assert=require('assert'),acorn=require('../../verification/tools/node_modules/acorn');
const s=fs.readFileSync('candidate/Rook710/game.js','utf8');const f=new Map(acorn.parse(s,{ecmaVersion:'latest'}).body.filter(n=>n.type==='FunctionDeclaration').map(n=>[n.id.name,s.slice(n.start,n.end)]));
class Classes{constructor(){this.s=new Set();}add(...ns){ns.forEach(n=>this.s.add(n));}remove(...ns){ns.forEach(n=>this.s.delete(n));}toggle(n,on){on?this.add(n):this.remove(n);}contains(n){return this.s.has(n);}}
const els={};function el(id){const e={id,classList:new Classes(),style:{},textContent:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;},querySelectorAll(){return[];}};let html='';Object.defineProperty(e,'innerHTML',{get:()=>html,set:v=>{html=v;if(id==='decisionConsole')for(const m of v.matchAll(/id="([^"]+)"/g))els[m[1]]=el(m[1]);}});return e;}
for(const id of ['decisionConsole','actionPanel','ltBidBar'])els[id]=el(id);
let overlay;const submissions=[];const ctx=vm.createContext({$:id=>els[id]||null,players:[{name:'Jerome',team:0}],myIndex:0,myName:'Jerome',minBid:100,includeRook:true,includeRed2:true,red2Points:20,includeRed1:false,includeOnes:true,shootMoonEnabled:true,isSpectator:false,_ltBidSuggested:0,game:{highestBid:95,scores:[0,0],phase:'bidding',currentPlayer:0},window:{matchMedia:()=>({matches:false})},hideBotStyleTip(){},nestAuctionLocked:()=>false,hideActionPanel(){els.decisionConsole.classList.add('hidden');},syncLandscapeBidBar(){},playSfx(){},submitBid:(...args)=>submissions.push(args),requestAnimationFrame(){},setTimeout(){},maybeRemindTurn(){},document:{querySelector:()=>overlay||null,createElement:()=>{const buttons={confirm:{},back:{addEventListener(k,v){this[k]=v;}}};const e={setAttribute(){},querySelector:q=>q==='[data-moon-confirm]'?buttons.confirm:buttons.back,remove(){overlay=null;},buttons};return e;},body:{appendChild:e=>overlay=e}}});
const names=['totalCountersInDeck','maxBid','isShootMoonBid','teamScoreForSeat','moonBidAllowed','bidCeilingFor','auctionHigh','auctionNextMin','showBidUI','closeApprovedMoonDeclaration','showApprovedMoonDeclaration'];vm.runInContext(names.map(n=>f.get(n)).join('\n'),ctx);
const event={preventDefault(){},stopPropagation(){}};let checks=0;
function start(high=95,score=0){ctx.game.highestBid=high;ctx.game.scores=[score,0];vm.runInContext('showBidUI()',ctx);checks++;}
function plus(n){for(let i=0;i<n;i++)els.bidPlus.onclick(event);}
start();assert.equal(els.bidConfirm.attrs['data-live-bid'],'100');els.bidPlus.onclick(event);assert.equal(els.bidValue.textContent,'105');assert.equal(els.bidConfirm.attrs['data-live-bid'],'105');els.bidMinus.onclick(event);assert.equal(els.bidValue.textContent,'100');els.bidMinus.onclick(event);assert.equal(els.bidValue.textContent,'100');els.bidConfirm.onclick(event);assert.equal(submissions.at(-1)[0],100);els.bidPassBtn.onclick(event);assert.equal(submissions.at(-1)[0],0);
start();plus(19);assert.equal(els.bidValue.textContent,'195');els.bidConfirm.onclick(event);assert.equal(submissions.at(-1)[0],195);
els.bidPlus.onclick(event);assert.equal(els.bidValue.textContent,'200');assert(els.bidConfirm.classList.contains('bid-shoot-moon'));els.bidConfirm.onclick(event);assert(overlay,'Actual original Moon function must create dialog');overlay.buttons.back.click(event);assert(!overlay);assert.equal(els.bidValue.textContent,'195');els.bidPlus.onclick(event);els.bidConfirm.onclick(event);overlay.buttons.confirm.onclick(event);assert.equal(submissions.at(-1)[0],200);assert.equal(submissions.at(-1)[1].moonConfirmed,true);
start(95,-1);plus(30);assert.equal(els.bidValue.textContent,'195');assert(!els.bidConfirm.classList.contains('bid-shoot-moon'));
ctx.includeOnes=false;start();plus(8);assert.equal(els.bidValue.textContent,'140');assert(els.bidConfirm.classList.contains('bid-shoot-moon'));ctx.includeOnes=true;
start(160);assert.equal(els.bidConfirm.attrs['data-live-bid'],'165');
for(let i=0;i<20;i++){start();plus(i%10);els.bidConfirm.onclick(event);assert.equal(submissions.at(-1)[0],100+5*(i%10));}
console.log('Original R706 bid function checks passed: +/-5, bounds, same live amount, BID/PASS, legitimate195, actual Moon dialog confirm/back, negative ceiling, option140 and 20 repeated auctions. These are VM tests, not bot games.');
